<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WH5000703" name="Default test" tests="1" failures="1" timestamp="30 Nov 2015 17:33:18 GMT" time="0.483" errors="0">
  <testcase name="Modify_an_employees_salary" time="0.473" classname="com.test.SalarySteps">
    <failure type="java.lang.RuntimeException" message="java.lang.AssertionError: expected [57750.0] but found [57751.0]">
      <![CDATA[java.lang.RuntimeException: java.lang.AssertionError: expected [57750.0] but found [57751.0]
	at com.legalmonkeys.test.AbstractCucumberTest.run(AbstractCucumberTest.java:76)
	at com.legalmonkeys.test.AbstractCucumberTest.run(AbstractCucumberTest.java:27)
	at com.test.SalarySteps.Modify_an_employees_salary(SalarySteps.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.lang.AssertionError: expected [57750.0] but found [57751.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at com.test.SalarySteps.the_payroll_for_the_employee_with_id_should_display_a_salary_of(SalarySteps.java:46)
	at âœ½.Then the payroll for the employee with id '3' should display a salary of 57750(src\test\resources\com\test\Salary.feature:15)
]]>
    </failure>
  </testcase> <!-- Modify_an_employees_salary -->
</testsuite> <!-- Default test -->
