<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WH5000703" name="com.test.BookSearchSteps" tests="1" failures="0" timestamp="30 Nov 2015 17:31:43 GMT" time="3.924" errors="1">
  <testcase name="Search_books_by_publication_year" time="3.924" classname="com.test.BookSearchSteps">
    <error type="java.lang.RuntimeException" message="java.lang.AssertionError: expected [Some other book] but found [Some other book a]">
      <![CDATA[java.lang.RuntimeException: java.lang.AssertionError: expected [Some other book] but found [Some other book a]
	at com.legalmonkeys.test.AbstractCucumberTest.run(AbstractCucumberTest.java:76)
	at com.legalmonkeys.test.AbstractCucumberTest.run(AbstractCucumberTest.java:27)
	at com.test.BookSearchSteps.Search_books_by_publication_year(BookSearchSteps.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.lang.AssertionError: expected [Some other book] but found [Some other book a]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.test.BookSearchSteps.verifyBookAtPosition(BookSearchSteps.java:57)
	at âœ½.And Book 1 should have the title 'Some other book'(src\test\resources\com\test\search_book.feature:10)
]]>
    </error>
  </testcase> <!-- Search_books_by_publication_year -->
</testsuite> <!-- com.test.BookSearchSteps -->
